"""Add project details fields

Revision ID: 04c302a90f01
Revises: 585443bd911e
Create Date: 2026-08-01 15:27:20.698217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c302a90f01'
down_revision: Union[str, Sequence[str], None] = '585443bd911e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('project', sa.Column('category', sa.String(), nullable=True))
    op.add_column('project', sa.Column('role', sa.String(), nullable=True))
    op.add_column('project', sa.Column('year', sa.String(), nullable=True))
    op.add_column('project', sa.Column('is_featured', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_unique_constraint(None, 'project', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_column('project', 'is_featured')
    op.drop_column('project', 'year')
    op.drop_column('project', 'role')
    op.drop_column('project', 'category')
    op.drop_column('project', 'slug')
    # ### end Alembic commands ###
