"""Add is_primary to tools

Revision ID: b9c5774c9e52
Revises: ff472073ec86
Create Date: 2026-08-04 17:56:44.184950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9c5774c9e52'
down_revision: Union[str, Sequence[str], None] = 'ff472073ec86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'is_primary')
    # ### end Alembic commands ###
